// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactHotkeys = require("react-hotkeys");

function make(onFocus, onBlur, component, children) {
  var tmp = { };
  if (onFocus) {
    tmp.onFocus = onFocus[0];
  }
  if (onBlur) {
    tmp.onBlur = onBlur[0];
  }
  if (component) {
    tmp.component = component[0];
  }
  return ReasonReact.wrapJsForReason(ReactHotkeys.FocusTrap, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
